#___________________________________________________________________________________
#
#                                  Set the verboses  
#___________________________________________________________________________________
#
/tracking/verbose 0
#
#___________________________________________________________________________________
#
#                                  Set the Physics and geometry  
#___________________________________________________________________________________
#
/Physics/addPhysics QGSP_BIC_EMY
/geometrySetup/selectGeometry Openbeam
#
#
#/rootanalysis/allowFileRewriting    No          # Yes / No (default), allow writing over files, or create file with new seed
#
#
# Initialize Geometry
#
/run/initialize
#
#___________________________________________________________________________________
#
#                                  Set the Ion  
#___________________________________________________________________________________
#
/gps/pos/type Point                   # options: Point (default), Beam, Plane, Surface or Volume
/gps/particle proton
/gps/pos/centre 0. 0. -100.0 cm
/gps/energy 200 MeV
/gps/direction 0 0 1                  # the beam direction
#
#___________________________________________________________________________________
#
#                                  Set the Visualisation  
#___________________________________________________________________________________
#							
#/vis/scene/create
#/vis/open OGLI
#/vis/scene/add/axes  
#/vis/scene/add/eventID
#/vis/open HepRepFile
#/vis/open VRML2FILE
#/vis/viewer/set/viewpointThetaPhi 54 154 deg
#/vis/viewer/zoomTo 1.0
#/vis/viewer/panTo -10 0 cm 
#/tracking/storeTrajectory 1
#/vis/scene/add/trajectories
#/vis/scene/endOfEventAction accumulate
#/vis/scene/endOfEventAction accumulate -1
#
#___________________________________________________________________________________
#
#                                  Set the Cut and Step Max  
#___________________________________________________________________________________
#
# 
/Step/waterPhantomStepMax 3 mm            # Set StepMax inside the Phantom
/Step/detectorStepMax 3 mm                # Set StepMax Only for World region

/Physics/setCuts 1  mm                    # Set cuts outside the detector 
/Physics/setTargetCuts 0.01 mm            # set cuts ONLY inside the Phantom
/Physics/setDetectorCuts 0.01 mm          # Set cuts ONLY inside the detector (Dosimeter)
#___________________________________________________________________________________
#
#                                  Set the Detector and Phantom  
#___________________________________________________________________________________ 
#
#
#/changePhantom/Shape  Cylinder                  
#/changePhantom/radius 10 cm
#/changePhantom/ZHalfLength 15 cm
#
/changePhantom/Shape  Box                  
/changePhantom/size 30 30 30  cm
#
/changePhantom/position 0 0 0 cm
/changePhantom/material Water
#
/changeDetector/insidethephantom No
/changeDetector/position 0 0 50 cm
/changeDetector/size 10 10 10 cm
/changeDetector/voxelSize 10 10 10 cm
/changeDetector/material NaI
#
/change/update 
/analysis/detector/secondary false   # Compute Dose and Fluence for secondary      
#
#___________________________________________________________________________________
#
#                                  Run  
#___________________________________________________________________________________ 
# 
/event/printEventNumber 1   # Display the event number during the run
/analysis/detector/writeDoseFile
#
#
/run/beamOn 1000
#

